version: '3.7'

services:
  web:
    container_name: blog
    build: .
    command: python /app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on: 
      - db

  db:
    container_name: db
    image: postgres:11
    env_file: 
      - .env
    ports:
      - 5432:5432
    volumes:
      - blog_db:/var/lib/postgresql/data/

volumes:
  blog_db: